version: '3.8'

services:
  frontend:
    build:
      context: ./frontend-web
    ports:
      - "5173:5173"
    environment:
      - VITE_APP_ENV=development

  signaling:
    build:
      context: ./signaling-server
    ports:
      - "3001:3001"

  coturn:
    image: coturn/coturn:latest
    container_name: coturn
    ports:
      - "3478:3478"
      - "3478:3478/udp"
      - "5349:5349"
      - "5349:5349/udp"
    volumes:
      - ./coturn/turnserver.conf:/etc/turnserver.conf
      - coturn_data:/var/lib/turn
    restart: unless-stopped

volumes:
  coturn_data: